steps:
  # Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    args: 
    - clone
    - https://github.com/danielwnn/FaceRecognition
    - demo

  # build the frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend:latest', './demo/frontend']

  # push the frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend:latest']

  # build the backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend:latest', './demo/backend']

  # push the frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend:latest']

  # run terraform
  - name: 'hashicorp/terraform'
    entrypoint: 'sh'
    args: 
    - '-c'
    - |
        cd ./demo/terraform
        terraform init
        terraform apply -auto-approve
        terraform destroy -auto-approve
    env:
    - 'TF_VAR_BUILD=$BUILD_ID'
    - 'TF_VAR_PROJECT_ID=$PROJECT_ID'

#  - name: 'gcr.io/cloud-builders/gcloud'
#    args:
#    - 'run'
#    - 'deploy'
#    - 'cloudrunservice'
#    - '--image'
#    - 'us-docker.pkg.dev/cloudrun/container/hello'
#    - '--region'
#    - 'us-central1'
#    - '--platform'
#    - 'managed'
#    - '--allow-unauthenticated'

images:
- 'gcr.io/$PROJECT_ID/frontend:latest'
- 'gcr.io/$PROJECT_ID/backend:latest'

# substitutions:
#   _SUB_VALUE_1: unused
#   _SUB_VALUE_2: v1.0 # default value
  
options:
  dynamic_substitutions: true

# timeout in 10 hours
timeout: 36000s