steps:
  # Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    args: 
    - clone
    - https://github.com/danielwnn/gcp_oauth2
    - source

  # build the frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcp_demo_app:latest', './source']

  # push the frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gcp_demo_app:latest']

  # deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run' 
    - 'deploy' 
    - 'gcp-demo-app'
    - '--image=gcr.io/$PROJECT_ID/gcp_demo_app:latest'
    - '--port=8080'
    - '--max-instances=5'
    - '--region=${_REGION}'
    - '--platform=managed'
    - '--set-secrets=/secret_manager/settings.json=app_settings:latest'
    - '--set-env-vars=APP_ENV=PROD,APP_PORT=8080,APP_CORS=*'
    - '--vpc-connector=projects/$PROJECT_ID/locations/${_REGION}/connectors/vpcconnector2'
    - '--allow-unauthenticated'

images:
- 'gcr.io/$PROJECT_ID/gcp_demo_app:latest'

substitutions:
  _REGION: us-west3
  
options:
  dynamic_substitutions: true

# timeout in 10 hours
timeout: 36000s